# golangci-lint configuration for mrva-go-hepc
# See https://golangci-lint.run/usage/configuration/ for options

run:
  timeout: 5m

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused code
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Find commonly misspelled words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security checks
    - gocritic      # Opinionated checks
    - errorlint     # Find incorrect error wrapping
    - bodyclose     # Check HTTP response body is closed
    - gocyclo       # Cyclomatic complexity

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict for this project

  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam

  revive:
    rules:
      - name: var-naming
        disabled: false
      - name: exported
        disabled: false

  gosec:
    excludes:
      - G204  # Allow subprocess execution
      - G304  # Allow file path from variables

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - errcheck  # Unchecked errors in tests are fine
        - gosec     # Security checks less important in tests
        - gocyclo   # Allow complex test setup functions

    # Allow variable shadowing in test files
    - path: _test\.go
      text: "shadow"

    # Exclude long lines for generated code
    - source: "^//go:generate "
      linters:
        - lll

  # Show all issues
  exclude-dirs:
    - vendor
    - bin

output:
  sort-results: true
